name: Format with Black

on:
  push:
    branches:
      - ci-test
  pull_request:
    branches:
      - ci-test

jobs:
  format:
    name: Auto-format Python Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Black
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Run Black Formatter
        run: black --check .

      - name: Auto-format if needed
        run: |
          black .
          git diff --quiet || (git config --global user.name 'github-actions' && git config --global user.email 'github-actions@github.com' && git commit -am "Auto-format Python code with Black" && git push)

